### ISSUE TITLE
Random YouTube Player image below initial video?

### ISSUE THREAD

**Issue by walesmd** [udacity/course-issues-ud117#1]
https://classroom.udacity.com/courses/ud117/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/354d9102-8b45-4a89-91df-6f5ec9022dbd

**Comment by forbiddenvoid** [comment]
@richardkalehoff Is this just a placeholder?

**Comment by richardkalehoff** [comment]
Yeah, that was just a placeholder. Somehow I skipped deleting it when I added the real video! :-D
