### ISSUE TITLE
Typo in paragraph

### ISSUE THREAD

**Issue by walesmd** [udacity/course-issues-ud117#2]
https://classroom.udacity.com/courses/ud117/lessons/74c2a096-61db-4302-9d65-6b7fa9b8c329/concepts/da27b611-6ac8-4c6f-a124-3ba94c06abad

Reads: Let's take a break for a second. At this state, the browse has received the bytes that've been sent by a server.

Should be: Let's take a break for a second. At this state, the browser has received the bytes that've been sent by a server.

**Comment by forbiddenvoid** [comment]
Fixed!
