### ISSUE TITLE
Not accessible in India

### ISSUE THREAD

**Issue by nimitbhargava** [udacity/course-issues-ud117#3]
https://www.udacity.com/course/javascript-and-the-dom--ud117 redirects to https://in.udacity.com/404

**Comment by richardkalehoff** [comment]
This issue has been submitted to an internal team for correction. I'll update this ticket when it's been resolved. Thanks for letting us know!

**Comment by hbkwong** [comment]
@nimitbhargava, let us know if you still run into trouble on this one. It should have since been resolved!
